### ISSUE TITLE
Adding Vertical map to tracker

### ISSUE THREAD

**Issue by Vodkanakas** [DorkmasterFlek/SOTN-AP-MapTracker#2]
This might just be a me thing but i modded the tracker to have a vertical map and added `Full` to have a `Vertical` and `Horizontal` selection. Might just be me that uses a vert monitor for their trackers but thought id float the idea. Also i dont know if the way i did it is correct so let me know what you think [https://github.com/Vodkanakas/SotN-poptracker-vertical-map-addon.git](url)

**Comment by DorkmasterFlek** [comment]
That's certainly a fine idea to add.  Actually I think I can make it so it switches between horizontal and vertical depending on the window size, so if you have your window resized to be taller than it is wide it switches automatically.  Also the link you provided doesn't seem to exist or work?  You might've made the repository private maybe?

**Comment by Vodkanakas** [comment]
Just seen this. Good catch its public now. And the option for horizontal and vertical switching would be awesome too.

**Comment by Vodkanakas** [comment]
> ...make it so it switches between horizontal and vertical depending on the window size, so if you have your window resized to be taller than it is wide it switches automatically....

awesome idea and added

**Comment by DorkmasterFlek** [comment]
Okay finally got around to looking at this again.  I believe your approach is correct in that in has to be a separate map image with both maps together in a vertical layout because getting the individual ones stacked vertically doesn't seem to work.  This means each location now has a normal or inverted map location, and a vertical map location for the other image.  I pushed a new release for this.
